'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _15127318_702478936610370_942627210_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15127318_702478936610370_942627210_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BADUY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BADUY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_tower2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-tower2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_tower21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-tower21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomberclick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomberclick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomberclick1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomberclick1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomberclick2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomberclick2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cartoon_Bomb_clip_art_hight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cartoon_Bomb_clip_art_hight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cartoon_Bomb_clip_art_hight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cartoon_Bomb_clip_art_hight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property damuhan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("damuhan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property damuhan1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("damuhan1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property damuhan2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("damuhan2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dynamite_7068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dynamite_7068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dynamite_70681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dynamite_70681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fuck_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fuck-start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gfBZVMa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gfBZVMa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gfBZVMa1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gfBZVMa1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageedit_1_5485607311() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageedit_1_5485607311", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageedit_3_8353790558() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageedit_3_8353790558", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings-logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property title_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title-page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wakaka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wakaka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property www_GIFCreator_me_V9WjYb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("www.GIFCreator.me_V9WjYb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zombie1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zombie1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombie2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombie2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombie22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombie22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombie221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombie221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
